FROM nowsci/samba-domain

#RUN samba-tool domain passwordsettings set --complexity=off \ 
#    && samba-tool domain passwordsettings set --max-pwd-age=0 \
#    && samba-tool domain passwordsettings set --history-length=0 \
#    && samba-tool domain passwordsettings set --min-pwd-age=0 \
#    && samba-tool domain passwordsettings set --min-pwd-length=4

#---> Release Port
EXPOSE 389
EXPOSE 445
